
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action ArchivoAction;

	private global::Gtk.Action NuevoDocumento;

	private global::Gtk.Action Abrir;

	private global::Gtk.Action Guardar;

	private global::Gtk.Action GuardarComo;

	private global::Gtk.Action printAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action EditarAction;

	private global::Gtk.Action copyAction;

	private global::Gtk.Action cutAction;

	private global::Gtk.Action pasteAction;

	private global::Gtk.Action VerAction;

	private global::Gtk.ToggleAction OcultarHerramientas;

	private global::Gtk.ToggleAction OcultarExplorador;

	private global::Gtk.Action HNuevo;

	private global::Gtk.Action HAbrir;

	private global::Gtk.Action HGuardar;

	private global::Gtk.Action HCopiar;

	private global::Gtk.Action HCortar;

	private global::Gtk.Action HPegar;

	private global::Gtk.Action BuscarAction;

	private global::Gtk.Action findAction;

	private global::Gtk.Action AyudaAction;

	private global::Gtk.Action SeleccionAction;

	private global::Gtk.Action SeleccionarTodoAction;

	private global::Gtk.Action AcercaDeCodeSEAction;

	private global::Gtk.Action Compilar;

	private global::Gtk.ToggleAction OcultarConsola;

	private global::Gtk.Action HerramientasAction;

	private global::Gtk.Action FuenteAction;

	private global::Gtk.Action dndMultipleAction;

	private global::Gtk.VBox Caja;

	private global::Gtk.MenuBar BarraMenu;

	private global::Gtk.HBox Caja1;

	private global::Gtk.Toolbar Herramientas;

	private global::Gtk.HPaned Caja2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.VPaned vpaned1;

	private global::Gtk.ScrolledWindow ScrollPagina;

	private global::Gtk.Notebook Pagina;

	private global::Gtk.ScrolledWindow ScrollConsola;

	private global::Gtk.TextView Consola;

	private global::Gtk.Statusbar Barra_de_Busqueda;

	private global::Gtk.Label Estado_de_Archivo;

	private global::Gtk.Entry Entrada;

	private global::Gtk.Button BtnBus;

	private global::Gtk.ScrolledWindow ScrollExplorador;

	private global::Gtk.Notebook Explorador;

	private global::Gtk.VBox vbox1;

	private global::Gtk.ComboBox Directorios;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView Archivos;

	private global::Gtk.Label LPortapapeles;

	private global::Gtk.Statusbar Estado;

	private global::Gtk.Label Caracteres;

	private global::Gtk.Label Lineas;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.ArchivoAction = new global::Gtk.Action("ArchivoAction", global::Mono.Unix.Catalog.GetString("Archivo"), null, null);
		this.ArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Archivo");
		w1.Add(this.ArchivoAction, null);
		this.NuevoDocumento = new global::Gtk.Action("NuevoDocumento", global::Mono.Unix.Catalog.GetString("Nuevo"), null, "gtk-new");
		this.NuevoDocumento.ShortLabel = global::Mono.Unix.Catalog.GetString("Nuevo");
		w1.Add(this.NuevoDocumento, "<Primary>n");
		this.Abrir = new global::Gtk.Action("Abrir", global::Mono.Unix.Catalog.GetString("Abrir"), null, "gtk-open");
		this.Abrir.ShortLabel = global::Mono.Unix.Catalog.GetString("Abrir");
		w1.Add(this.Abrir, null);
		this.Guardar = new global::Gtk.Action("Guardar", global::Mono.Unix.Catalog.GetString("Guardar"), null, "gtk-save");
		this.Guardar.ShortLabel = global::Mono.Unix.Catalog.GetString("Guardar");
		w1.Add(this.Guardar, null);
		this.GuardarComo = new global::Gtk.Action("GuardarComo", global::Mono.Unix.Catalog.GetString("Guardar Como"), null, "gtk-save-as");
		this.GuardarComo.ShortLabel = global::Mono.Unix.Catalog.GetString("Guardar Como");
		w1.Add(this.GuardarComo, null);
		this.printAction = new global::Gtk.Action("printAction", global::Mono.Unix.Catalog.GetString("Exportar a PDF"), null, "gtk-print");
		this.printAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exportar");
		w1.Add(this.printAction, null);
		this.quitAction = new global::Gtk.Action("quitAction", global::Mono.Unix.Catalog.GetString("Salir"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir");
		w1.Add(this.quitAction, null);
		this.EditarAction = new global::Gtk.Action("EditarAction", global::Mono.Unix.Catalog.GetString("Editar"), null, null);
		this.EditarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Editar");
		w1.Add(this.EditarAction, null);
		this.copyAction = new global::Gtk.Action("copyAction", global::Mono.Unix.Catalog.GetString("Copiar"), null, "gtk-copy");
		this.copyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Copiar");
		w1.Add(this.copyAction, null);
		this.cutAction = new global::Gtk.Action("cutAction", global::Mono.Unix.Catalog.GetString("Cortar"), null, "gtk-cut");
		this.cutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cortar");
		w1.Add(this.cutAction, null);
		this.pasteAction = new global::Gtk.Action("pasteAction", global::Mono.Unix.Catalog.GetString("Pegar"), null, "gtk-paste");
		this.pasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Pegar");
		w1.Add(this.pasteAction, null);
		this.VerAction = new global::Gtk.Action("VerAction", global::Mono.Unix.Catalog.GetString("Ver"), null, null);
		this.VerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Ver");
		w1.Add(this.VerAction, null);
		this.OcultarHerramientas = new global::Gtk.ToggleAction("OcultarHerramientas", global::Mono.Unix.Catalog.GetString("Ocultar Herramientas"), null, null);
		this.OcultarHerramientas.ShortLabel = global::Mono.Unix.Catalog.GetString("Ocultar Herramientas");
		w1.Add(this.OcultarHerramientas, null);
		this.OcultarExplorador = new global::Gtk.ToggleAction("OcultarExplorador", global::Mono.Unix.Catalog.GetString("Ocultar Explorador"), null, null);
		this.OcultarExplorador.ShortLabel = global::Mono.Unix.Catalog.GetString("Ocultar Explorador");
		w1.Add(this.OcultarExplorador, null);
		this.HNuevo = new global::Gtk.Action("HNuevo", global::Mono.Unix.Catalog.GetString("HNuevo"), global::Mono.Unix.Catalog.GetString("Nuevo"), "gtk-new");
		this.HNuevo.ShortLabel = global::Mono.Unix.Catalog.GetString("HNuevo");
		w1.Add(this.HNuevo, null);
		this.HAbrir = new global::Gtk.Action("HAbrir", null, global::Mono.Unix.Catalog.GetString("Abrir"), "gtk-open");
		w1.Add(this.HAbrir, null);
		this.HGuardar = new global::Gtk.Action("HGuardar", null, global::Mono.Unix.Catalog.GetString("Guardar"), "gtk-save");
		w1.Add(this.HGuardar, null);
		this.HCopiar = new global::Gtk.Action("HCopiar", null, global::Mono.Unix.Catalog.GetString("Copiar"), "gtk-copy");
		w1.Add(this.HCopiar, null);
		this.HCortar = new global::Gtk.Action("HCortar", null, global::Mono.Unix.Catalog.GetString("Cortar"), "gtk-cut");
		w1.Add(this.HCortar, null);
		this.HPegar = new global::Gtk.Action("HPegar", null, global::Mono.Unix.Catalog.GetString("Pegar"), "gtk-paste");
		w1.Add(this.HPegar, null);
		this.BuscarAction = new global::Gtk.Action("BuscarAction", global::Mono.Unix.Catalog.GetString("Buscar"), null, null);
		this.BuscarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Buscar");
		w1.Add(this.BuscarAction, null);
		this.findAction = new global::Gtk.Action("findAction", global::Mono.Unix.Catalog.GetString("Buscar..."), null, "gtk-find");
		this.findAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Buscar...");
		w1.Add(this.findAction, null);
		this.AyudaAction = new global::Gtk.Action("AyudaAction", global::Mono.Unix.Catalog.GetString("Ayuda"), null, null);
		this.AyudaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Ayuda");
		w1.Add(this.AyudaAction, null);
		this.SeleccionAction = new global::Gtk.Action("SeleccionAction", global::Mono.Unix.Catalog.GetString("Seleccion"), null, null);
		this.SeleccionAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Seleccion");
		w1.Add(this.SeleccionAction, null);
		this.SeleccionarTodoAction = new global::Gtk.Action("SeleccionarTodoAction", global::Mono.Unix.Catalog.GetString("Seleccionar Todo"), null, null);
		this.SeleccionarTodoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Seleccionar Todo");
		w1.Add(this.SeleccionarTodoAction, null);
		this.AcercaDeCodeSEAction = new global::Gtk.Action("AcercaDeCodeSEAction", global::Mono.Unix.Catalog.GetString("Acerca de CodeSE"), null, null);
		this.AcercaDeCodeSEAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Acerca de CodeSE");
		w1.Add(this.AcercaDeCodeSEAction, null);
		this.Compilar = new global::Gtk.Action("Compilar", null, global::Mono.Unix.Catalog.GetString("Compilar"), "gtk-go-up");
		w1.Add(this.Compilar, null);
		this.OcultarConsola = new global::Gtk.ToggleAction("OcultarConsola", global::Mono.Unix.Catalog.GetString("Ocultar Consola"), null, null);
		this.OcultarConsola.ShortLabel = global::Mono.Unix.Catalog.GetString("Ocultar Consola");
		w1.Add(this.OcultarConsola, null);
		this.HerramientasAction = new global::Gtk.Action("HerramientasAction", global::Mono.Unix.Catalog.GetString("Herramientas"), null, null);
		this.HerramientasAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Herramientas");
		w1.Add(this.HerramientasAction, null);
		this.FuenteAction = new global::Gtk.Action("FuenteAction", global::Mono.Unix.Catalog.GetString("Fuente"), null, null);
		this.FuenteAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Fuente");
		w1.Add(this.FuenteAction, null);
		this.dndMultipleAction = new global::Gtk.Action("dndMultipleAction", global::Mono.Unix.Catalog.GetString("Recientes"), null, "gtk-dnd-multiple");
		this.dndMultipleAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Recientes");
		w1.Add(this.dndMultipleAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "CodeSyntaxEditor";
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.Caja = new global::Gtk.VBox();
		this.Caja.Name = "Caja";
		this.Caja.Spacing = 6;
		// Container child Caja.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='BarraMenu'><menu name='ArchivoAction' action='ArchivoAction'><menuitem name='NuevoDocumento' action='NuevoDocumento'/><menuitem name='Abrir' action='Abrir'/><menuitem name='Guardar' action='Guardar'/><menuitem name='GuardarComo' action='GuardarComo'/><menuitem name='printAction' action='printAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='EditarAction' action='EditarAction'><menuitem name='copyAction' action='copyAction'/><menuitem name='cutAction' action='cutAction'/><menuitem name='pasteAction' action='pasteAction'/></menu><menu name='SeleccionAction' action='SeleccionAction'><menuitem name='SeleccionarTodoAction' action='SeleccionarTodoAction'/></menu><menu name='BuscarAction' action='BuscarAction'><menuitem name='findAction' action='findAction'/></menu><menu name='VerAction' action='VerAction'><menuitem name='OcultarHerramientas' action='OcultarHerramientas'/><menuitem name='OcultarExplorador' action='OcultarExplorador'/><menuitem name='OcultarConsola' action='OcultarConsola'/></menu><menu name='HerramientasAction' action='HerramientasAction'><menuitem name='FuenteAction' action='FuenteAction'/></menu><menu name='AyudaAction' action='AyudaAction'><menuitem name='AcercaDeCodeSEAction' action='AcercaDeCodeSEAction'/></menu></menubar></ui>");
		this.BarraMenu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/BarraMenu")));
		this.BarraMenu.Name = "BarraMenu";
		this.Caja.Add(this.BarraMenu);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.Caja[this.BarraMenu]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child Caja.Gtk.Box+BoxChild
		this.Caja1 = new global::Gtk.HBox();
		this.Caja1.Name = "Caja1";
		this.Caja1.Spacing = 6;
		// Container child Caja1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='Herramientas'><toolitem name='HNuevo' action='HNuevo'/><toolitem name='HAbrir' action='HAbrir'/><toolitem name='HGuardar' action='HGuardar'/><toolitem name='HCopiar' action='HCopiar'/><toolitem name='HCortar' action='HCortar'/><toolitem name='HPegar' action='HPegar'/><toolitem name='Compilar' action='Compilar'/></toolbar></ui>");
		this.Herramientas = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/Herramientas")));
		this.Herramientas.Name = "Herramientas";
		this.Herramientas.Orientation = ((global::Gtk.Orientation)(1));
		this.Herramientas.ShowArrow = false;
		this.Herramientas.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.Herramientas.IconSize = ((global::Gtk.IconSize)(1));
		this.Caja1.Add(this.Herramientas);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.Caja1[this.Herramientas]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child Caja1.Gtk.Box+BoxChild
		this.Caja2 = new global::Gtk.HPaned();
		this.Caja2.CanFocus = true;
		this.Caja2.Name = "Caja2";
		this.Caja2.Position = 568;
		// Container child Caja2.Gtk.Paned+PanedChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vpaned1 = new global::Gtk.VPaned();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 269;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.ScrollPagina = new global::Gtk.ScrolledWindow();
		this.ScrollPagina.CanFocus = true;
		this.ScrollPagina.Name = "ScrollPagina";
		this.ScrollPagina.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ScrollPagina.Gtk.Container+ContainerChild
		global::Gtk.Viewport w4 = new global::Gtk.Viewport();
		w4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport1.Gtk.Container+ContainerChild
		this.Pagina = new global::Gtk.Notebook();
		this.Pagina.CanFocus = true;
		this.Pagina.Name = "Pagina";
		this.Pagina.CurrentPage = -1;
		w4.Add(this.Pagina);
		this.ScrollPagina.Add(w4);
		this.vpaned1.Add(this.ScrollPagina);
		global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.ScrollPagina]));
		w7.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.ScrollConsola = new global::Gtk.ScrolledWindow();
		this.ScrollConsola.Name = "ScrollConsola";
		this.ScrollConsola.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ScrollConsola.Gtk.Container+ContainerChild
		this.Consola = new global::Gtk.TextView();
		this.Consola.CanDefault = true;
		this.Consola.CanFocus = true;
		this.Consola.Name = "Consola";
		this.ScrollConsola.Add(this.Consola);
		this.vpaned1.Add(this.ScrollConsola);
		global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.ScrollConsola]));
		w9.Resize = false;
		w9.Shrink = false;
		this.vbox3.Add(this.vpaned1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vpaned1]));
		w10.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.Barra_de_Busqueda = new global::Gtk.Statusbar();
		this.Barra_de_Busqueda.Name = "Barra_de_Busqueda";
		this.Barra_de_Busqueda.Spacing = 6;
		// Container child Barra_de_Busqueda.Gtk.Box+BoxChild
		this.Estado_de_Archivo = new global::Gtk.Label();
		this.Estado_de_Archivo.Name = "Estado_de_Archivo";
		this.Estado_de_Archivo.Justify = ((global::Gtk.Justification)(2));
		this.Barra_de_Busqueda.Add(this.Estado_de_Archivo);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.Barra_de_Busqueda[this.Estado_de_Archivo]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child Barra_de_Busqueda.Gtk.Box+BoxChild
		this.Entrada = new global::Gtk.Entry();
		this.Entrada.CanFocus = true;
		this.Entrada.Name = "Entrada";
		this.Entrada.IsEditable = true;
		this.Entrada.InvisibleChar = '•';
		this.Barra_de_Busqueda.Add(this.Entrada);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.Barra_de_Busqueda[this.Entrada]));
		w12.Position = 2;
		// Container child Barra_de_Busqueda.Gtk.Box+BoxChild
		this.BtnBus = new global::Gtk.Button();
		this.BtnBus.CanFocus = true;
		this.BtnBus.Name = "BtnBus";
		this.BtnBus.UseUnderline = true;
		this.BtnBus.Label = global::Mono.Unix.Catalog.GetString("Buscar");
		this.Barra_de_Busqueda.Add(this.BtnBus);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.Barra_de_Busqueda[this.BtnBus]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox3.Add(this.Barra_de_Busqueda);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.Barra_de_Busqueda]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.Caja2.Add(this.vbox3);
		global::Gtk.Paned.PanedChild w15 = ((global::Gtk.Paned.PanedChild)(this.Caja2[this.vbox3]));
		w15.Resize = false;
		// Container child Caja2.Gtk.Paned+PanedChild
		this.ScrollExplorador = new global::Gtk.ScrolledWindow();
		this.ScrollExplorador.CanFocus = true;
		this.ScrollExplorador.Name = "ScrollExplorador";
		this.ScrollExplorador.ShadowType = ((global::Gtk.ShadowType)(1));
		this.ScrollExplorador.WindowPlacement = ((global::Gtk.CornerType)(2));
		// Container child ScrollExplorador.Gtk.Container+ContainerChild
		global::Gtk.Viewport w16 = new global::Gtk.Viewport();
		w16.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.Explorador = new global::Gtk.Notebook();
		this.Explorador.CanFocus = true;
		this.Explorador.Name = "Explorador";
		this.Explorador.CurrentPage = 0;
		// Container child Explorador.Gtk.Notebook+NotebookChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Directorios = global::Gtk.ComboBox.NewText();
		this.Directorios.Name = "Directorios";
		this.vbox1.Add(this.Directorios);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.Directorios]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Archivos = new global::Gtk.TreeView();
		this.Archivos.CanFocus = true;
		this.Archivos.Name = "Archivos";
		this.GtkScrolledWindow.Add(this.Archivos);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w19.Position = 1;
		this.Explorador.Add(this.vbox1);
		// Notebook tab
		this.LPortapapeles = new global::Gtk.Label();
		this.LPortapapeles.Name = "LPortapapeles";
		this.LPortapapeles.LabelProp = global::Mono.Unix.Catalog.GetString("Explorador");
		this.Explorador.SetTabLabel(this.vbox1, this.LPortapapeles);
		this.LPortapapeles.ShowAll();
		w16.Add(this.Explorador);
		this.ScrollExplorador.Add(w16);
		this.Caja2.Add(this.ScrollExplorador);
		global::Gtk.Paned.PanedChild w23 = ((global::Gtk.Paned.PanedChild)(this.Caja2[this.ScrollExplorador]));
		w23.Resize = false;
		w23.Shrink = false;
		this.Caja1.Add(this.Caja2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.Caja1[this.Caja2]));
		w24.Position = 1;
		this.Caja.Add(this.Caja1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.Caja[this.Caja1]));
		w25.Position = 1;
		// Container child Caja.Gtk.Box+BoxChild
		this.Estado = new global::Gtk.Statusbar();
		this.Estado.Name = "Estado";
		this.Estado.Homogeneous = true;
		this.Estado.Spacing = 6;
		// Container child Estado.Gtk.Box+BoxChild
		this.Caracteres = new global::Gtk.Label();
		this.Caracteres.Name = "Caracteres";
		this.Caracteres.LabelProp = global::Mono.Unix.Catalog.GetString("Caracteres: 0");
		this.Estado.Add(this.Caracteres);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.Estado[this.Caracteres]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child Estado.Gtk.Box+BoxChild
		this.Lineas = new global::Gtk.Label();
		this.Lineas.Name = "Lineas";
		this.Lineas.LabelProp = global::Mono.Unix.Catalog.GetString("Lineas: 0");
		this.Estado.Add(this.Lineas);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.Estado[this.Lineas]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		this.Caja.Add(this.Estado);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.Caja[this.Estado]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.Add(this.Caja);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 779;
		this.DefaultHeight = 448;
		this.Barra_de_Busqueda.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.NuevoDocumento.Activated += new global::System.EventHandler(this.OnNuevoDocumentoActivated);
		this.Abrir.Activated += new global::System.EventHandler(this.OnAbrirActivated);
		this.Guardar.Activated += new global::System.EventHandler(this.OnGuardarActivated);
		this.GuardarComo.Activated += new global::System.EventHandler(this.OnGuardarComoActivated);
		this.printAction.Activated += new global::System.EventHandler(this.OnExportarPDFActivated);
		this.quitAction.Activated += new global::System.EventHandler(this.OnSalirActivated);
		this.copyAction.Activated += new global::System.EventHandler(this.OnNuevoDocumentoActivated);
		this.OcultarHerramientas.Activated += new global::System.EventHandler(this.OnOcultarHerramientasToggled);
		this.OcultarExplorador.Activated += new global::System.EventHandler(this.OnOcultarExploradorToggled);
		this.HNuevo.Activated += new global::System.EventHandler(this.OnNuevoDocumentoActivated);
		this.HAbrir.Activated += new global::System.EventHandler(this.OnAbrirActivated);
		this.HGuardar.Activated += new global::System.EventHandler(this.OnGuardarActivated);
		this.HCopiar.Activated += new global::System.EventHandler(this.OnHCopiarActivated);
		this.HCortar.Activated += new global::System.EventHandler(this.OnHCortarActivated);
		this.HPegar.Activated += new global::System.EventHandler(this.OnHPegarActivated);
		this.findAction.Activated += new global::System.EventHandler(this.OnFindActionActivated);
		this.SeleccionarTodoAction.Activated += new global::System.EventHandler(this.OnSeleccionarTodoActionActivated);
		this.AcercaDeCodeSEAction.Activated += new global::System.EventHandler(this.OnAcercaDeCodeSEActionActivated);
		this.Compilar.Activated += new global::System.EventHandler(this.OnCompilarActivated);
		this.OcultarConsola.Toggled += new global::System.EventHandler(this.OnOcultarConsolaToggled);
		this.FuenteAction.Activated += new global::System.EventHandler(this.OnFuenteActionActivated);
		this.BtnBus.Clicked += new global::System.EventHandler(this.OnBtnBusActivated);
		this.Directorios.Changed += new global::System.EventHandler(this.OnDirectoriosChanged);
	}
}
